from pydantic import BaseModel, Field
from typing import Optional


class Course(BaseModel):
    id: Optional[int] = Field(None, description="The ID of the course, automatically generated by the server")
    title: str = Field(..., description="The title of the course")
    description: str = Field(..., description="The description of the course")
